### ISSUE TITLE
Show (a gif) in normal size

### ISSUE THREAD

**Issue by Cycymomo** [ro-ka/gifalicious#8]
Another idea : Actually, I am able to "Show in big" any single GIF of my collection. 
By clicking "Show in big", the gif is alone per page. I'd like to see this gif in normal size. 

Maybe add an option (see in big, see in normal, see in small) ?

Thanks

**Comment by ro-ka** [comment]
What's the advantage of viewing a GIF in original size?

If it is because of some GIFs not fitting on a screen: I want to improve the design so the GIFs always fit on the screen. Have to experiment with that.

**Comment by Cycymomo** [comment]
Because of the poor quality of some GIF. In big size, there is a lot of pixel in such case.

_I want to improve the design so the GIFs always fit on the screen. Have to experiment with that._
:+1:

**Comment by ro-ka** [comment]
Okay, will check how I can resolve that.   :)

Thanks for the input!
